import { Geist, JetBrains_Mono } from "next/font/google";
import "./globals.css";



const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${jetBrainsMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
